version: '3.8'

services:
  database:
    image: postgres:15
    environment:
      POSTGRES_DB: household_tasks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    
  backend:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@database:5432/household_tasks
    depends_on:
      - database
    volumes:
      - ./server:/app
      - /app/node_modules
      
  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: