version: '3.8'

services:
  database:
    image: postgres:15
    environment:
      POSTGRES_DB: household_tasks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@database:5432/household_tasks
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
    depends_on:
      - database
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev
      
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=/api
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  postgres_data: