services:
  database:
    image: postgres:15
    container_name: household-db
    environment:
      POSTGRES_DB: household_tasks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /mnt/user/appdata/household-tasks/data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    
  backend:
    image: ghcr.io/einstein1403/haushaltsapp-backend:latest
    container_name: household-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@database:5432/household_tasks
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3001
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
      
  frontend:
    image: ghcr.io/einstein1403/haushaltsapp-frontend:latest
    container_name: household-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=/api
    depends_on:
      - backend
    restart: unless-stopped