services:
  database:
    image: postgres:15
    container_name: household-db
    environment:
      POSTGRES_DB: household_tasks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    
  app:
    build: .
    container_name: household-app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD:-password}@database:5432/household_tasks
      - JWT_SECRET=${JWT_SECRET:-dev-secret-key-change-in-production}
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: